package modelo;

public enum Estilo {
    IMPRESIONISMO,
    POSTIMPRESIONISMO,
    OLEO_SOBRE_TELA,
    CUBISMO,
    SURREALISMO,
    EXPRESIONISMO,
    REALISMO,
    ABSTRACCION,
    ARTE_POP,
    RENACIMIENTO,
    BARROCO
}